### PR TITLE
Fixed spelling mistakes XD

### PR DESCRIPTION
**Pull request by FantasyIsBae**
Sorry @LegitSoulja I'm a little OCD xd

Also could jsGen-phpGen be an npm package ?

### CODE REVIEW

**Comment by LegitSoulja** [comment]
lol

**Comment by FantasyIsBae** [comment]
I know , im "Different" lol

**Comment by LegitSoulja** [comment]
and "npm" eh, not yet. I haven't tested this with nodejs. I don't even want to -_-

**Comment by LegitSoulja** [comment]
but it's supported

**Comment by LegitSoulja** [comment]
and this isn't no where near done yet.

**Comment by FantasyIsBae** [comment]
I could do some testing if you like :)

**Comment by LegitSoulja** [comment]
I just created this yesterday lol, and sure, if you undetstand the usage. I haven't applied comments yet

**Comment by LegitSoulja** [comment]
As to the compressed version of jsGen.min.js, the function/class name isn't jsGen, as changed on compressed. exports.jsGen = new "Class Name"?

**Comment by FantasyIsBae** [comment]
Yea i do somewhat understand it , i mean im somewhat new to working with someone (Not a noob XD) , but ill give it a good shot

**Comment by FantasyIsBae** [comment]
And ok , ill test both :)

**Comment by FantasyIsBae** [comment]
@LegitSoulja If you dont mind me asking , what are your pc specs ?

**Comment by LegitSoulja** [comment]
On steroids.

**Comment by FantasyIsBae** [comment]
http://i.imgur.com/LZVaLpV.png

This is your pc XD

**Comment by FantasyIsBae** [comment]
@LegitSoulja

**Pull request merged**
